templateDict = {
	"data_sources": None,
    "report_title" : None,
	"report_date" : None,
	"shape_area" : None, 
	"pixel_area" : None,
	"map_elevation": None,
	"map_naturenetwork": None,
	"map_satellite": None,
	"map_slope": None,
	"map_canopy": None,
	"map_carbonstoragewoodlands": None,
	"map_carbonstoragenonwoodlands": None,
	"map_carbonstoragetopsoil": None,
	"map_carbonseqwoodlands": None,
	"map_carbonseqnonwoodlands": None,
	"map_soilerosion": None,
	"map_recreation": None,
	"map_soiltype": None,
	# "water_map": water_map,
	"map_floodrisk": None,
	"map_landcover": None,
	"map_biodiversity": None,
	"map_pollination": None,
	"estimated_visitors": None,
	"map_hotspots": None,
	"table1": None,
	"table2": None,
	"tableA2": None,
	"tableB1": None,
	"tableB2": None,
	"tableB3": None,
	"tableB4": None,
	"tableB5": None,
	"tableB6": None
}